// Settings
export const ERROR = 'ERROR';
export const LOADING = 'LOADING';

// Recipe
export const GET_RECIPE = 'GET_RECIPE';
export const SET_RECIPE_SETTINGS = 'SET_RECIPE_SETTINGS';
export const SET_RECIPE_ID = 'SET_RECIPE_ID';

// Recipe Formular
export const SET_RECIPE_ERROR = 'SET_RECIPE_ERROR'
export const SET_RECIPE_TITLE = 'SET_RECIPE_TITLE';
export const SET_RECIPE_PORTION = 'SET_RECIPE_PORTION';
export const SET_RECIPE_SOURCE = 'SET_RECIPTE_SOURCE';
export const ADD_RECIPE_KEYWORDS = 'ADD_RECIPE_KEYWORDS';
export const REMOVE_RECIPE_KEYWORDS = 'REMOVE_RECIPE_KEYWORDS'
export const SET_RECIPE_INGREDIENTS = 'SET_RECIPE_INGREDIENTS';
export const SET_RECIPE_STEPS = 'SET_RECIPE_STEPS';
export const SET_RECIPE_PICTURES = 'SET_RECIPE_PICTURES';
export const SET_RECIPE_TIME = 'SET_RECIPE_TIME';
export const SET_RECIPE_CATEGORIES = 'SET_RECIPE_CATEGORIES';
export const SET_RECIPE_FORMULAR = 'SET_RECIPE_FORMULAR';
export const SET_RECIPE_BLOCKED = 'SET_RECIPE_BLOCKED';