// Recipe
export const SET_RECIPE_TITLE = 'SET_RECIPE_TITLE';
export const SET_RECIPE_PORTION = 'SET_RECIPE_PORTION';
export const SET_RECIPE_SOURCE = 'SET_RECIPTE_SOURCE';
export const ADD_RECIPE_KEYWORDS = 'ADD_RECIPE_KEYWORDS';
export const REMOVE_RECIPE_KEYWORDS = 'REMOVE_RECIPE_KEYWORDS'
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const SET_STEPS = 'SET_STEPS';